[server]
port=5555

[node]
detect-drivers = false
hub="http://192.168.1.2:4444"

[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName": "firefox", "moz:firefoxOptions.binary": "C:\Users\Yulia_Klimova\geckodriver.exe"}'
max-sessions = 5
